version: "3.8"

services:
  frontend:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=http://192.168.94.204:8081
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://192.168.94.204:8081
